优化launch

diff --git a/deb/usr/bin/waydroid-launch b/deb/usr/bin/waydroid-launch
--- a/deb/usr/bin/waydroid-launch
+++ b/deb/usr/bin/waydroid-launch
@@ -1,7 +1,20 @@
 #!/bin/bash
+timeout=1
 if [[ ! -e $HOME/.local/share/waydroid/data/data/$1 ]]; then
     echo 未安装，立即安装！
-    waydroid app install $2
+    if [[ -f /usr/share/waydroid/apk/`basename $1`.apk ]]; then
+        (
+            waydroid-install-dpkg $2
+            if [[ $? == 0 ]]; then
+                echo '#安装完成！' 
+            else
+                echo '#安装超时！'
+            fi
+        ) | zenity --progress --pulsate
+    else
+        zenity --error --text="Error"
+    fi
+
     exit
 fi
 waydroid app launch $1
